package Day_67;

import java.util.ArrayList;
import java.util.HashMap;

public class HospitalService {
	ArrayList<Hospital> hospitals = new ArrayList<>();
	int code = 100;
	
	public int addHospital(Hospital h){
		h.setHospitalCode(code);
		hospitals.add(h);
		code++;
		return h.getHospitalCode();
	}
	
	 public HashMap<Integer,String> getHospitals(){
		 HashMap<Integer,String> map = new HashMap<Integer,String>();
		 for(Hospital h:hospitals) {
			 map.put(h.getHospitalCode(), h.getHospitalName());
		 }
		 return map;
	 }

	 public Hospital getHospitalDetails(int hospitalCode ) {
		 for(Hospital h:hospitals) {
			 if(h.getHospitalCode()==hospitalCode) {
				 return h;
			 }
		 }
		 return null;
	 }
}

/*
A class HospitalService is given to you. Implement the following features in the class.
Methods : public 
addHospital(): This method should receive hospital details 
 as arguments and add to ArrayList of type Hospital and return the generated hospital 
code.
Note : Hospital Code is not given as argument but it should be 
 autogenerated while creating object. It should start from 100.
 getHospitals() : This method should return existing hospitals 
names and its codes in the form of Map variable that contains Hospital 
Code as key (Integer) and Hospital name as Value (String).
 getHospitalDetails() : This method should receive hospital code 
as argument and return the matching object of hospital after searching in 
the ArrayList. Return null if object not found.

*/